[2023-12-06T17:10:39.356+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: good_morning_1.get_cur_rate scheduled__2023-12-06T16:10:00+00:00 [queued]>
[2023-12-06T17:10:39.451+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: good_morning_1.get_cur_rate scheduled__2023-12-06T16:10:00+00:00 [queued]>
[2023-12-06T17:10:39.454+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-12-06T17:10:39.525+0000] {taskinstance.py:1382} INFO - Executing <Task(DockerOperator): get_cur_rate> on 2023-12-06 16:10:00+00:00
[2023-12-06T17:10:39.562+0000] {standard_task_runner.py:57} INFO - Started process 2338 to run task
[2023-12-06T17:10:39.573+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'good_morning_1', 'get_cur_rate', 'scheduled__2023-12-06T16:10:00+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/good_mornig.py', '--cfg-path', '/tmp/tmp6tk_qhhc']
[2023-12-06T17:10:39.587+0000] {standard_task_runner.py:85} INFO - Job 36: Subtask get_cur_rate
[2023-12-06T17:10:39.749+0000] {task_command.py:416} INFO - Running <TaskInstance: good_morning_1.get_cur_rate scheduled__2023-12-06T16:10:00+00:00 [running]> on host 856bd231061d
[2023-12-06T17:10:40.102+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='mdv' AIRFLOW_CTX_DAG_ID='good_morning_1' AIRFLOW_CTX_TASK_ID='get_cur_rate' AIRFLOW_CTX_EXECUTION_DATE='2023-12-06T16:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-06T16:10:00+00:00'
[2023-12-06T17:10:40.204+0000] {docker.py:343} INFO - Starting docker container from image debian:buster-slim
[2023-12-06T17:10:40.255+0000] {docker.py:351} WARNING - Using remote engine or docker-in-docker and mounting temporary volume from host is not supported. Falling back to `mount_tmp_dir=False` mode. You can set `mount_tmp_dir` parameter to False to disable mounting and remove the warning
[2023-12-06T17:10:40.797+0000] {docker.py:413} INFO - Hello world!
[2023-12-06T17:10:41.214+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=good_morning_1, task_id=get_cur_rate, execution_date=20231206T161000, start_date=20231206T171039, end_date=20231206T171041
[2023-12-06T17:10:41.312+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-12-06T17:10:41.385+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
